-- AlterTable
ALTER TABLE "Email" ADD COLUMN "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Email" ADD COLUMN "isStarred" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Email" ADD COLUMN "isArchived" BOOLEAN NOT NULL DEFAULT false;
