-- CreateTable
CREATE TABLE "AuDevAnalysis" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "asin" TEXT NOT NULL,
    "marketplace" TEXT NOT NULL DEFAULT 'AU',
    "productTitle" TEXT,
    "productImage" TEXT,
    "price" REAL,
    "rating" REAL,
    "reviews" INTEGER,
    "bsr" INTEGER,
    "categoryPath" TEXT,
    "monthlySales" INTEGER,
    "monthlyRevenue" REAL,
    "sellerName" TEXT,
    "sellerNation" TEXT,
    "fulfillment" TEXT,
    "marketOverview" TEXT,
    "diffPlan" TEXT,
    "profitModel" TEXT,
    "actionPlan" TEXT,
    "generatedImages" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "errorMessage" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "userId" TEXT NOT NULL,
    CONSTRAINT "AuDevAnalysis_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
